apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cerebro-kube-small-1
  region: ca-central-1
  version: "1.26"
availabilityZones: 
  - ca-central-1b
  - ca-central-1a
managedNodeGroups:
- name: ng-controller
  labels:
    role: controller
  instanceType: t3.2xlarge
  desiredCapacity: 1
  volumeSize: 200
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
- name: ng-worker
  labels:
    role: worker
  instanceTypes: 
  - g4dn.12xlarge
  desiredCapacity: 2
  volumeSize: 200
  ami: ami-0d962eb122177eb6b
  amiFamily: AmazonLinux2
  availabilityZones: 
  - ca-central-1b
  - ca-central-1a
  spot: False
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
  overrideBootstrapCommand: |
    #!/bin/bash

    /etc/eks/bootstrap.sh cerebro-kube-small-1 --container-runtime containerd
