# Worker StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cluster.username }}-cerebro-mop-worker
  namespace: default
spec:
  podManagementPolicy: Parallel
  serviceName: {{ .Values.cluster.username }}-workersvc
  replicas: 0
  selector:
    matchLabels:
      app: cerebro-mop-worker
      user: {{ .Values.cluster.username }}
  template:
    metadata:
      labels:
        app: cerebro-mop-worker
        user: {{ .Values.cluster.username }}
    spec:
      hostname: $WORKER_ID_SELF
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: brightcomputing.com/node-category
                operator: In
                values:
                - gaudi
      serviceAccountName: {{ .Values.cluster.username }}
      containers:
      - name: mop-container
        image: {{ .Values.controller.git.image }}
        imagePullPolicy: Always
        command: [ "/bin/bash", "/cerebro-repo/cerebro-core/mop/run_mop.sh"]
        workingDir: /cerebro-repo/cerebro-core
        resources:
          limits:
            habana.ai/gaudi: {{ .Values.cluster.resourceLimits.workerGPU }}
            memory: {{ .Values.cluster.resourceLimits.workerMemory }}
            cpu: {{ .Values.cluster.resourceLimits.workerCPU }}
          requests:
            habana.ai/gaudi: {{ .Values.cluster.resourceRequests.workerGPU }}
            memory: {{ .Values.cluster.resourceRequests.workerMemory }}
            cpu: {{ .Values.cluster.resourceRequests.workerCPU }}
        ports:
          - containerPort: {{ .Values.worker.rpcPort }}
        env:
        - name: WORKER_ID_SELF
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: POD_TYPE
          value: "mop"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoPath }}
        - name: user-repo
          mountPath: {{ .Values.controller.volumes.userRepoPath }}
        - name: data-storage-worker
          subPathExpr: $(WORKER_ID_SELF)
          mountPath: {{ .Values.worker.workerDataPath }}
        - name: data-storage
          mountPath: {{ .Values.controller.volumes.dataPath }}
        - name: metrics-storage
          mountPath: {{ .Values.controller.volumes.metricsPath }}
        - name: checkpoint-storage
          mountPath: {{ .Values.controller.volumes.checkpointPath }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: cerebro-repo
        hostPath:
          path: /voyager/ceph/users/{{ .Values.cluster.username }}/volumes{{ .Values.controller.volumes.cerebroRepoPath }}
          type: DirectoryOrCreate
      - name: user-repo
        hostPath:
          path: /voyager/ceph/users/{{ .Values.cluster.username }}/volumes{{ .Values.controller.volumes.userRepoPath }}
          type: DirectoryOrCreate
      - name: data-storage-worker
        hostPath:
          path: /voyager/ceph/users/{{ .Values.cluster.username }}/volumes/worker_storage
          type: DirectoryOrCreate
      - name: data-storage
        hostPath:
          path: /voyager/ceph/users/{{ .Values.cluster.username }}/volumes{{ .Values.controller.volumes.dataPath }}
          type: DirectoryOrCreate
      - name: metrics-storage
        hostPath:
          path: /voyager/ceph/users/{{ .Values.cluster.username }}/volumes{{ .Values.controller.volumes.metricsMountPath }}
          type: DirectoryOrCreate
      - name: checkpoint-storage
        hostPath:
          path: /voyager/ceph/users/{{ .Values.cluster.username }}/volumes{{ .Values.controller.volumes.checkpointPath }}
          type: DirectoryOrCreate