# Worker StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cluster.username }}-cerebro-worker
  namespace: {{ .Values.cluster.namespace }}
spec:
  podManagementPolicy: Parallel
  serviceName: {{ .Values.cluster.username }}-mopworkersvc
  replicas: 0
  selector:
    matchLabels:
      app: cerebro-mop-worker
      user: {{ .Values.cluster.username }}
  template:
    metadata:
      labels:
        app: cerebro-mop-worker
        user: {{ .Values.cluster.username }}
    spec:
      hostname: $WORKER_ID_SELF
      securityContext:
        runAsUser: {{ .Values.cluster.userUID }}
        runAsGroup: {{ .Values.cluster.userGID }}
        fsGroup: {{ .Values..cluster.userGID }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: brightcomputing.com/node-category
                operator: In
                values:
                - gaudi
      serviceAccountName: {{ .Values.cluster.username }}
      containers:
      - name: mop-container
        image: {{ .Values.controller.image.core }}
        imagePullPolicy: Always
        workingDir: /cerebro-core
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/sync.sh; /cerebro-core/cerebro/mop/run_mop.sh" ]
        resources:
          limits:
            habana.ai/gaudi: {{ .Values.cluster.resourceLimits.workerGPU }}
            memory: {{ .Values.cluster.resourceLimits.workerMemory }}
            cpu: {{ .Values.cluster.resourceLimits.workerCPU }}
          requests:
            habana.ai/gaudi: {{ .Values.cluster.resourceRequests.workerGPU }}
            memory: {{ .Values.cluster.resourceRequests.workerMemory }}
            cpu: {{ .Values.cluster.resourceRequests.workerCPU }}
        ports:
          - containerPort: {{ .Values.worker.rpcPort }}
        env:
        - name: PLATFORM
          value: {{ .Values.controller.image.platform }}
        - name: CLOUD_PROVIDER
          value: {{ .Values.cluster.cloudProvider }}
        - name: GIT_SYNC_REPO
          value: {{ .Values.controller.image.gitURL }}
        - name: GIT_SYNC_BRANCH
          value: {{ .Values.controller.image.gitBranch }}
        - name: USERNAME
          value: {{ .Values.cluster.username }}
        - name: NAMESPACE
          value: {{ .Values.cluster.namespace }}
        - name: WORKER_ID_SELF
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: POD_TYPE
          value: "mop"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: user-code
          mountPath: {{ .Values.controller.volumes.userCodePath }}
        - name: data-storage-worker
          subPathExpr: $(WORKER_ID_SELF)
          mountPath: {{ .Values.worker.workerDataPath }}
        - name: data-storage
          mountPath: {{ .Values.controller.volumes.dataPath }}
        - name: metrics-storage
          mountPath: {{ .Values.controller.volumes.metricsPath }}
        - name: checkpoint-storage
          mountPath: {{ .Values.controller.volumes.checkpointPath }}
        - name: kvs-storage
          mountPath: {{ .Values.controller.volumes.kvsPath }}
        - name: kube-config-volume
          mountPath: /root/.kube/config
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: user-code
        hostPath:
          path: {{ .Values.controller.volumes.baseHostPath }}{{ .Values.controller.volumes.userCodePath }}
          type: DirectoryOrCreate
      - name: data-storage-worker
        hostPath:
          path: {{ .Values.controller.volumes.baseHostPath }}{{ .Values.worker.workerDataPath }}
          type: DirectoryOrCreate
      - name: data-storage
        hostPath:
          path: {{ .Values.controller.volumes.baseHostPath }}{{ .Values.controller.volumes.dataPath }}
          type: DirectoryOrCreate
      - name: metrics-storage
        hostPath:
          path: {{ .Values.controller.volumes.baseHostPath }}{{ .Values.controller.volumes.metricsPath }}
          type: DirectoryOrCreate
      - name: checkpoint-storage
        hostPath:
          path: {{ .Values.controller.volumes.baseHostPath }}{{ .Values.controller.volumes.checkpointPath }}
          type: DirectoryOrCreate
      - name: kvs-storage
        hostPath:
          path: {{ .Values.controller.volumes.baseHostPath }}{{ .Values.controller.volumes.kvsPath }}
          type: DirectoryOrCreate
      - name: kube-config-volume
        hostPath:
          path: "/home/{{ .Values.cluster.username }}/.kube/config"
          type: File