# Controller Persistent Volume Claim

# cerebro code pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-repo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.cerebroRepoCapacity }}
---
# user code pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-repo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.userRepoCapacity }}
---
# Checkpoint pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-checkpoint-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.checkpointCapacity }}
---
# Config pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.configCapacity }}
---
# Data pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.sharedDataCapacity }}
---
# Metrics pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-metrics-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.metricsCapacity }}