# Controller Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cluster.username }}-cerebro-controller
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: cerebro-controller
    user: {{ .Values.cluster.username }}
spec:
  selector:
    matchLabels:
      app: cerebro-controller
      user: {{ .Values.cluster.username }}
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro-controller
        user: {{ .Values.cluster.username }}
    spec:
      hostname: controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: brightcomputing.com/node-category
                operator: In
                values:
                - goya
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - cerebro-controller
              topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Values.cluster.username }}
      initContainers:
      - name: git-sync
        image: {{ .Values.controller.git.gitSyncImage }}
        imagePullPolicy: Always
        volumeMounts:
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoPath }}
        env:
        - name: GIT_SYNC_DIR
          value: cerebro-core
        - name: GIT_SYNC_REPO
          value: {{ .Values.controller.git.cerebroRepoURL }}
        - name: GIT_SYNC_BRANCH
          value: {{ .Values.controller.git.cerebroRepoBranch }}
        - name: GIT_SYNC_ROOT
          value: {{ .Values.controller.volumes.cerebroRepoPath }}
        - name: GIT_SYNC_SERVER
          value: {{ .Values.creds.gitServer }}
        securityContext:
          runAsUser: 0
      containers:
      - name: controller
        image: {{ .Values.controller.git.image }}
        imagePullPolicy: Always
        command: [ "/bin/bash", "/cerebro-repo/cerebro-core/init.sh"]
        workingDir: /cerebro-repo/cerebro-core
        resources:
          limits:
            cpu: {{ .Values.cluster.resourceLimits.controllerMemory }}
            memory: {{ .Values.cluster.resourceLimits.controllerCPU }}
          requests:
            cpu: {{ .Values.cluster.resourceRequests.controllerMemory }}
            memory: {{ .Values.cluster.resourceRequests.controllerCPU }}
        env:
        - name: ML_METRICS_LOGDIR
          value: {{ .Values.controller.volumes.metricsMountPath }}
        - name: USERNAME
          value: {{ .Values.cluster.username }}
        - name: NAMESPACE
          value: {{ .Values.cluster.namespace }}
        volumeMounts:
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoPath }}
        - name: user-repo
          mountPath: {{ .Values.controller.volumes.userRepoPath }}
        - name: checkpoint-storage
          mountPath: {{ .Values.controller.volumes.checkpointPath }}
        - name: data-storage
          mountPath: {{ .Values.controller.volumes.dataPath }}
        - name: metrics-storage
          mountPath: {{ .Values.controller.volumes.metricsPath }}
        ports:
        - containerPort: {{ .Values.controller.services.jupyterPort }}
          name: jupyter-port
        - containerPort: {{ .Values.controller.services.tensorboardPort }}
          name: tnsrbrd-port
      volumes:
      - name: cerebro-repo
        hostPath:
          path: "{{ .Values.controller.volumes.baseHostPath }}:{{ .Values.controller.volumes.cerebroRepoPath }}"
          type: DirectoryOrCreate
      - name: user-repo
        hostPath:
          path: "{{ .Values.controller.volumes.baseHostPath }}:{{ .Values.controller.volumes.userRepoPath }}"
          type: DirectoryOrCreate
      - name: checkpoint-storage
        hostPath:
          path: "{{ .Values.controller.volumes.baseHostPath }}:{{ .Values.controller.volumes.checkpointPath }}"
          type: DirectoryOrCreate
      - name: metrics-storage
        hostPath:
          path: "{{ .Values.controller.volumes.baseHostPath }}:{{ .Values.controller.volumes.metricsPath }}"
          type: DirectoryOrCreate
      - name: data-storage
        hostPath:
          path: "{{ .Values.controller.volumes.baseHostPath }}:{{ .Values.controller.volumes.dataPath }}"
          type: DirectoryOrCreate
